Nahary
rabehasy/php.symfony5-demo pull request #4
Opened 2022-05-15 13:42 UTC by Naharintsoa

Ireto ary ny modif_

2022-05-16 20:15 UTC, rabehasy requested changes

2022-05-16 20:15 UTC, rabehasy commented on src/Entity/Articles.php
> +    private $article_id;
Rehefa mi créé "propriété" i Nahary dia aza asiana `_id` amin'ny farany. Satria i Symfony no manao an'iny automatiquement rehefa any anaty base de données

`article` dia ampy. 

Na zany na tsy zany, raha ny eto dia `tag` no tokony izy fa tsy `article`

2022-05-16 20:15 UTC, rabehasy commented on src/Entity/Articles.php
> +        $this->article_id = new ArrayCollection();
Mitovy am commentaire-ko teo ambony ihany

2022-05-16 20:15 UTC, rabehasy commented on src/Entity/Articles.php
> +    }
Mitovy am commentaire-ko teo ambony ihany

2022-05-16 20:15 UTC, rabehasy commented on src/Entity/Tag.php
> +    private $tag_id;
Mitovy am commentaire-ko teo ambony ihany amin'ilay anarana propriété

2022-05-16 20:15 UTC, rabehasy commented on src/Entity/Tag.php
> +     * @ORM\ManyToMany(targetEntity=Articles::class, inversedBy="article_id")
Mitovy am commentaire-ko teo ambony ihany -> `article_id`

2022-05-16 20:15 UTC, rabehasy commented on templates/frontend/contact.html.twig
> +          <p><input type="submit" name="submit" value="Envoyer"
Mety ny ohatr'izao

Fa misy fika hafa koa amin'ny Symfony fanamboarana formulaire. 

Jerena amin'ny manaraka, fa raha ity exercice voalohany ity aloha tsy maninona ohatr'izao ity template ty

2022-05-16 20:15 UTC, rabehasy commented on src/Entity/Tag.php
> +        $this->tag_id = $tag_id;
Mitovy am commentaire-ko teo ambony ihany

2022-05-17 07:18 UTC, Naharintsoa commented on src/Entity/Categorie.php
>          return $this;
ok efa modifié lay anarana = > Category.php

2022-05-17 09:27 UTC, Naharintsoa commented on src/Entity/Categorie.php
>      public function getCreatedate(): ?\DateTimeInterface
Mazava ! Ok daholo ireto

2022-05-17 10:43 UTC, Naharintsoa commented on src/Entity/Articles.php
> +    private $article_id;
Ao tsara

2022-05-17 10:47 UTC, Naharintsoa commented on src/Entity/Articles.php
> +    }
Vita ihany koa

2022-05-17 10:53 UTC, Naharintsoa commented on src/Entity/Tag.php
> +    private $tag_id;
ok

2022-05-17 10:55 UTC, Naharintsoa commented on src/Entity/Tag.php
> +     * @ORM\ManyToMany(targetEntity=Articles::class, inversedBy="article_id")
ok

2022-05-17 10:56 UTC, Naharintsoa commented on templates/frontend/contact.html.twig
> +          <p><input type="submit" name="submit" value="Envoyer"
ok, jerena amin'ny manaraka

2022-05-17 10:57 UTC, Naharintsoa commented on src/Entity/Articles.php
> +        $this->article_id = new ArrayCollection();
ok

2022-05-17 10:59 UTC, Naharintsoa commented on src/Entity/Tag.php
> +        $this->tag_id = $tag_id;
ok

2022-05-18 20:50 UTC, rabehasy approved these changes

2022-05-18 20:50 UTC, rabehasy commented on src/Controller/FrontendController.php
> +        return $this->render('frontend/contact.html.twig', [
Fixed now

2022-05-18 20:53 UTC, merged